import httpClient from '../services/httpClient'
import {
  checkVerifyStatus,
  getRegistrationAvailability,
  getCurrentUser,
  loginUser,
  logoutUser,
  oauthLogin,
  registerUser,
  resendVerificationEmail,
} from './auth'
import {
  completeTask,
  generateSummary,
  getChatHistory,
  getDayExecution,
  getNotes,
  getSummary,
  saveNotes,
  saveSummaryNotes,
  saveVideoProgress,
  streamChatMessage,
  submitDepth,
  submitPractical,
  submitQuiz,
} from './execution'
import { createTopic, getTopicStatus, getTopics, retryTopic } from './topic'
import { deleteUserAccount, getUserProfile, updateUserProfile } from './user'

export {
  checkVerifyStatus,
  completeTask,
  createTopic,
  deleteUserAccount,
  generateSummary,
  getChatHistory,
  getDayExecution,
  getNotes,
  getRegistrationAvailability,
  getSummary,
  getTopicStatus,
  getTopics,
  getUserProfile,
  getCurrentUser,
  httpClient,
  loginUser,
  logoutUser,
  oauthLogin,
  registerUser,
  resendVerificationEmail,
  retryTopic,
  saveNotes,
  saveSummaryNotes,
  saveVideoProgress,
  streamChatMessage,
  submitDepth,
  submitPractical,
  submitQuiz,
  updateUserProfile,
}
